In [171]:
import pandas as pd
file_name = "test_out/plsbefast.csv"
df = pd.read_csv(file_name)[['config.post', 'config.algo', 'config.env_name', 'mdim_mean', 'cdim_mean', 'mdim_nan_mean', 'mdim_std', 'ureward_mean', 'ureward_std', 'nreward_mean', 'nreward_std', 'len_mean',
                             'cdim_nan_mean']]#, 'config.post']]
df

,config.post,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
0,NaN,ppo,Walker2DBulletEnv-v0,1.689780,5.556138,1.689780,0.118989,2111.364508,10.776165,33.376486,0.170349,1000.0,5.556138
1,<function mdim_div_stable at 0x7fea80eb6a60>,ppo,Walker2DBulletEnv-v0,1.710201,6.176765,1.710201,0.163493,2256.862814,20.632931,35.676526,0.326166,1000.0,6.176765

In [162]:
df.loc[(df['config.algo'] == 'td3') & (df['config.post']=='iden')]

,config.post,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
1,iden,td3,Walker2DBulletEnv-v0,1.296572,10.881104,1.296572,0.192960,2052.887746,568.973756,2052.887692,568.973735,917.5,10.881104
5,iden,td3,HalfCheetahBulletEnv-v0,1.374065,8.956402,1.374065,0.082803,2826.124755,14.489177,2826.124731,14.489161,1000.0,8.956402
9,iden,td3,HopperBulletEnv-v0,1.240117,6.282698,1.240117,0.086367,2679.315193,28.479300,2679.315210,28.479283,998.0,6.282698
13,iden,td3,AntBulletEnv-v0,1.710029,9.815890,1.710029,0.101798,3313.426100,41.518409,3313.426123,41.518435,1000.0,9.815890
17,iden,td3,ReacherBulletEnv-v0,0.634532,4.283022,0.634532,0.090405,12.441167,5.627356,12.441167,5.627355,150.0,4.283022

In [163]:
df.loc[(df['config.algo'] == 'td3') & (df['config.post']=='mdim')]

,config.post,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
21,mdim,td3,Walker2DBulletEnv-v0,1.361735,12.093958,1.361735,0.060973,2479.075673,9.955165,2479.075635,9.955122,1000.0,12.093958
25,mdim,td3,HalfCheetahBulletEnv-v0,1.425879,9.621824,1.425879,0.078070,2933.105438,10.332936,2933.105469,10.332892,1000.0,9.621824
29,mdim,td3,HopperBulletEnv-v0,1.229490,7.177447,1.229490,0.080380,2807.424241,265.218231,2807.424280,265.218216,970.6,7.177447
33,mdim,td3,AntBulletEnv-v0,1.577786,8.762514,1.577786,0.086235,3462.284244,17.471718,3462.284204,17.471767,1000.0,8.762514
37,mdim,td3,ReacherBulletEnv-v0,0.608696,5.171530,0.608696,0.061743,12.028339,6.191481,12.028339,6.191481,150.0,5.171530

In [164]:
df.loc[(df['config.algo'] == 'td3') & (df['config.post']=='cdim')]

,config.post,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
41,cdim,td3,Walker2DBulletEnv-v0,1.401049,11.670240,1.401049,0.108253,2462.718077,11.193213,2462.718115,11.193218,999.5,11.670240
45,cdim,td3,HalfCheetahBulletEnv-v0,1.372961,9.380960,1.372961,0.060095,2952.863392,8.858368,2952.863354,8.858425,1000.0,9.380960
49,cdim,td3,HopperBulletEnv-v0,1.235878,7.501268,1.235878,0.126799,2650.850480,674.254960,2650.850464,674.254946,912.9,7.501268
53,cdim,td3,AntBulletEnv-v0,1.660564,8.465205,1.660564,0.123259,3505.385156,12.827411,3505.385156,12.827385,1000.0,8.465205
57,cdim,td3,ReacherBulletEnv-v0,0.611170,4.296913,0.611170,0.062618,12.436666,6.181959,12.436665,6.181960,150.0,4.296913

In [167]:
import pandas as pd
file_name = "keepers/ppo_a2c_100.csv"
df = pd.read_csv(file_name)[['config.train', 'config.algo', 'config.env_name', 'mdim_mean', 'mdim_nan_mean', 'mdim_std', 'ureward_mean', 'ureward_std', 'nreward_mean', 'nreward_std', 'len_mean']]
df

,config.train,config.algo,config.env_name,mdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean
0,False,ppo,Walker2DBulletEnv-v0,1.963476,1.963476,0.132894,2111.364508,10.776165,33.376486,0.170349,1000.0
1,False,a2c,Walker2DBulletEnv-v0,NaN,0.933991,NaN,905.954950,276.436180,38.493285,11.745547,909.8
2,False,ppo,HalfCheetahBulletEnv-v0,1.817264,1.817264,0.092955,2908.169612,38.828683,26.925796,0.359502,1000.0
3,False,a2c,HalfCheetahBulletEnv-v0,2.125698,2.125698,0.159355,2097.729587,38.287512,32.796229,0.598593,1000.0
4,False,ppo,HopperBulletEnv-v0,1.613065,1.613065,0.084308,2537.098882,263.534898,29.168804,3.029838,966.4
5,False,a2c,HopperBulletEnv-v0,1.091405,1.091405,0.126574,768.694332,346.149968,13.005136,5.856330,534.7
6,True,ppo,Walker2DBulletEnv-v0,1.152133,1.152133,0.153365,1868.071133,27.120454,29.530500,0.428721,1000.0
7,True,a2c,Walker2DBulletEnv-v0,0.937504,0.937504,0.007751,1001.688195,2.008234,42.560912,0.085329,1000.0
8,True,ppo,HalfCheetahBulletEnv-v0,1.681537,1.681537,0.066835,2554.963687,70.415481,23.655577,0.651954,1000.0
9,True,a2c,HalfCheetahBulletEnv-v0,1.615918,1.615918,0.092567,1988.964804,31.281858,31.095784,0.489065,1000.0
10,True,ppo,HopperBulletEnv-v0,1.419093,1.419093,0.040547,2541.667945,41.778377,29.221334,0.480323,995.7
11,True,a2c,HopperBulletEnv-v0,1.483334,1.483334,0.025717,2239.173504,24.568394,37.883403,0.415660,1000.0

In [168]:
df.loc[(df['config.algo'] == 'ppo') & (df['config.train']==False)]

,config.train,config.algo,config.env_name,mdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean
0,False,ppo,Walker2DBulletEnv-v0,1.963476,1.963476,0.132894,2111.364508,10.776165,33.376486,0.170349,1000.0
2,False,ppo,HalfCheetahBulletEnv-v0,1.817264,1.817264,0.092955,2908.169612,38.828683,26.925796,0.359502,1000.0
4,False,ppo,HopperBulletEnv-v0,1.613065,1.613065,0.084308,2537.098882,263.534898,29.168804,3.029838,966.4

In [169]:
df.loc[(df['config.algo'] == 'ppo') & (df['config.train']==True)]

,config.train,config.algo,config.env_name,mdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean
6,True,ppo,Walker2DBulletEnv-v0,1.152133,1.152133,0.153365,1868.071133,27.120454,29.530500,0.428721,1000.0
8,True,ppo,HalfCheetahBulletEnv-v0,1.681537,1.681537,0.066835,2554.963687,70.415481,23.655577,0.651954,1000.0
10,True,ppo,HopperBulletEnv-v0,1.419093,1.419093,0.040547,2541.667945,41.778377,29.221334,0.480323,995.7

In [123]:
df.loc[(df['config.algo'] == 'td3') & (df['config.train']==False)]

,config.train,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
2,False,td3,Walker2DBulletEnv-v0,NaN,NaN,1.385299,NaN,2052.887746,568.973756,2052.887692,568.973735,917.5,10.117610
8,False,td3,HalfCheetahBulletEnv-v0,1.418637,9.325105,1.418637,0.094321,2826.124755,14.489177,2826.124731,14.489161,1000.0,9.325105
14,False,td3,HopperBulletEnv-v0,1.233501,5.482480,1.233501,0.105169,2679.315193,28.479300,2679.315210,28.479283,998.0,5.482480
20,False,td3,AntBulletEnv-v0,1.661431,8.565321,1.661431,0.124652,3313.426100,41.518409,3313.426123,41.518435,1000.0,8.565321
26,False,td3,ReacherBulletEnv-v0,NaN,NaN,NaN,NaN,12.441167,5.627356,12.441167,5.627355,150.0,NaN

In [127]:
df.loc[(df['config.algo'] == 'tqc') & (df['config.train']==False)]

,config.train,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
5,False,tqc,Walker2DBulletEnv-v0,NaN,NaN,1.391070,NaN,2418.166841,755.757666,2418.166795,755.757647,907.8,7.512200
11,False,tqc,HalfCheetahBulletEnv-v0,1.420859,4.526387,1.420859,0.063570,3683.604083,17.602738,3683.604077,17.602688,1000.0,4.526387
17,False,tqc,HopperBulletEnv-v0,1.306618,7.230764,1.306618,0.061219,2693.198463,12.604214,2693.198462,12.604205,1000.0,7.230764
23,False,tqc,AntBulletEnv-v0,1.645090,10.461982,1.645090,0.219703,3418.044591,171.086013,3418.044580,171.085960,1000.0,10.461982
29,False,tqc,ReacherBulletEnv-v0,NaN,NaN,NaN,NaN,15.299590,8.984380,15.299589,8.984379,150.0,NaN

In [130]:
df.loc[(df['config.algo'] == 'ddpg') & (df['config.train']==False)]

,config.train,config.algo,config.env_name,mdim_mean,cdim_mean,mdim_nan_mean,mdim_std,ureward_mean,ureward_std,nreward_mean,nreward_std,len_mean,cdim_nan_mean
4,False,ddpg,Walker2DBulletEnv-v0,NaN,NaN,1.113990,NaN,1015.078698,790.522622,1015.078680,790.522611,529.5,9.309079
10,False,ddpg,HalfCheetahBulletEnv-v0,1.263753,7.039615,1.263753,0.105984,2088.962962,95.069826,2088.963000,95.069814,1000.0,7.039615
16,False,ddpg,HopperBulletEnv-v0,NaN,NaN,0.785918,NaN,949.633707,509.286164,949.633704,509.286161,357.1,4.220627
22,False,ddpg,AntBulletEnv-v0,2.241480,12.098584,2.241480,0.109829,2394.688964,62.809585,2394.689014,62.809541,1000.0,12.098584
28,False,ddpg,ReacherBulletEnv-v0,NaN,NaN,NaN,NaN,16.514616,10.717869,16.514617,10.717869,150.0,NaN

In [126]:
import os
#os.makedirs('./keepers/')
df.to_csv(f"./keepers/{file_name}")

FileExistsError: [Errno 17] File exists: './keepers/'